// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0mLm2yaiiuX-_ujLNu5v8rLQUYmRaVmg',
    appId: '1:11517768711:android:5eea7fb7d6d43e336e66a2',
    messagingSenderId: '11517768711',
    projectId: 'humble-warrior-c70b5',
    storageBucket: 'humble-warrior-c70b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNlQikRE9QvcDMN1ZNtKFyQbctSPwH1M8',
    appId: '1:11517768711:ios:4787a138004be0236e66a2',
    messagingSenderId: '11517768711',
    projectId: 'humble-warrior-c70b5',
    storageBucket: 'humble-warrior-c70b5.appspot.com',
    androidClientId: '11517768711-l3vb1jrbek38h4tms9a3f7olp2vo9223.apps.googleusercontent.com',
    iosClientId: '11517768711-972i9vlsus07hb0pq8ea1rfr3nfbsm7p.apps.googleusercontent.com',
    iosBundleId: 'com.hw.int',
  );
}
