// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnM-Y6B6Xqm3hVLdNgvXa6UHuSOO9EGas',
    appId: '1:340829922874:android:062f81e74783000dec7703',
    messagingSenderId: '340829922874',
    projectId: 'hwapp-78661',
    databaseURL: 'https://hwapp-78661-default-rtdb.firebaseio.com',
    storageBucket: 'hwapp-78661.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAfi551nKdVc8D1__iDiLIiy0exnBvvHpE',
  //   appId: '1:340829922874:ios:83560ad0e0b4bd2bec7703',
  //   messagingSenderId: '340829922874',
  //   projectId: 'hwapp-78661',
  //   databaseURL: 'https://hwapp-78661-default-rtdb.firebaseio.com',
  //   storageBucket: 'hwapp-78661.appspot.com',
  //   iosClientId: '340829922874-o8qpij3h27hbmn0fjai7di4k31pnj1c1.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.humbleWarrior',
  // );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfi551nKdVc8D1__iDiLIiy0exnBvvHpE',
    appId: '1:340829922874:ios:3c000c87aa1f844fec7703',
    messagingSenderId: '340829922874',
    projectId: 'hwapp-78661',
    databaseURL: 'https://hwapp-78661-default-rtdb.firebaseio.com',
    storageBucket: 'hwapp-78661.appspot.com',
    iosClientId:
        '340829922874-r63ac8cku8jdtgd6epcpu6rfosaqa96r.apps.googleusercontent.com',
    iosBundleId: 'com.humble.warrior',
  );
}
